---
title: "Reporte de Ventas MBM Servicio de Envíos"
output: 
  beamer_presentation: 
    toc: false
    keep_tex: true
    latex_engine: xelatex
    includes:
        in_header: nw_report_header.tex
classoption: "aspectratio=169"        
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      fig.showtext = TRUE)

options(tinytex.verbose = TRUE)

library(tidyverse)
library(knitr)
library(kableExtra)
library(lubridate)
library(scales)

library(showtext)
font.add("opensans", regular = "OpenSans-Regular.ttf")
showtext.auto()
setwd("/home/manuel/Documentos/automatedReports/")
source("scripts/functions.R")
```


```{r runall, include=FALSE}
out <- NULL
out <- c(out, knitr::knit_child('mbm-child-report_1.Rmd'))
out <- c(out, knitr::knit_child('mbm-child-report.Rmd'))
out <- c(out, knitr::knit_child('mbm-child-report_2.Rmd'))
out <- c(out, knitr::knit_child('mbm-child-report_3.Rmd'))
out <- c(out, knitr::knit_child('mbm-child-report_4.Rmd'))
out <- c(out, knitr::knit_child('mbm-child-report_5.Rmd'))
```

`r paste(out, collapse = '\n')` 
