```{r, echo=FALSE}
cat_loop_name <- paste("Gráfico al", as.character(Sys.Date()), 
                       "Marítimo", sep=" ") 
```

# `r cat_loop_name`
\begin{columns}[T]
    \begin{column}{0.90\textwidth} %first column
    \scriptsize
```{r, out.width="\\textwidth", fig.width=3.5,fig.height=1.8,fig.asp=NA}
  resumen_data_mar <- resumen_data_armar[resumen_data_armar$Envio == "MARITIMO",]
  resumen_data_mar$Mes <- stringr::str_sub(resumen_data_mar$Mes, 1, 3)
  ggplot(data=resumen_data_mar, aes(x=reorder(Mes, orden), y=Ganancias)) +
  geom_bar(stat="identity", fill = "#8cc7a1", width = 0.5) +
  geom_text(aes(label=Ganancias), vjust=-0.3, color="black", size=1.5) +
  theme(
  axis.text.y = element_text(size = rel(1), hjust = 0),
  axis.text.x = element_text(size = rel(1), face = "bold"),
  panel.background = element_rect(fill = "grey98"),
  plot.background = element_rect(fill = "grey98"),
  axis.title = element_blank(),
  panel.border = element_blank(),
  panel.grid.major.x = element_line(color = "gray90")
  )
```
    \normalsize
    \end{column}
\end{columns}
